apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::719640821092:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-3YFPOaSDW9fQ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::719640821092:user/sai
      username: sai
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-09T10:00:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1154"
  uid: bc1a950d-797d-48fb-8e16-b21eec78b8ba
